#cloud-config
package_upgrade: true
packages:
  - nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    defer: true
    content: |
      server {
        listen 80;
        server_name localhost;
        root /var/www/html;
        
        location / {
          try_files $uri $uri/ =404;
        }
      }
runcmd:
  - mkdir -p /var/www/html  # Create directory for website files
  - cp -r /src/* /var/www/html/  # Copy HTML/CSS/JS files to the default NGINX directory
  - chown -R www-data:www-data /var/www/html  # Set permissions
  - chmod -R 755 /var/www/html  # Ensure read/execute permissions
  - service nginx restart  # Restart NGINX to apply the new configuration
