#cloud-config
package_upgrade: true
packages:
  - nginx
write_files:
  - owner: www-data:www-data
    path: /etc/nginx/sites-available/default
    defer: true
    content: |
      server {
        listen 80;
        server_name localhost;
        root /home/myapp/public;
        
        location / {
          try_files $uri $uri/ =404;
        }
      }
runcmd:
  - mkdir -p /home/myapp/public  # Create directory for website files
  - cp -r /src/* /home/myapp/public/  # Copy HTML/CSS/JS files to public directory
  - chown -R www-data:www-data /home/myapp/public  # Set permissions
  - service nginx restart  # Restart NGINX to apply the new configuration
